version: '2'
services:
  jira:
    image: cptactionhank/atlassian-jira-software:7.4.3
    restart: always
    links:
      - database
    external_links:
      - crowd/crowd:crowd
    volumes:
      - jira-data:/var/atlassian/jira


  database:
    image: postgres:9.4
    restart: always
    volumes:
      - jira-db-data:/var/lib/postgresql/data