version: '2'
services:
  crowd:
    image: blacklabelops/crowd:3.0.1
    volumes:
      - ${DATA_PATH}:/var/atlassian/crowd
    restart: always
    environment:
      CROWD_PROXY_NAME: ${PROXY_NAME}
      CROWD_PROXY_PORT: ${PROXY_PORT}
      CROWD_PROXY_SCHEME: ${PROXY_SCHEME}
      CROWD_URL: "http://localhost:8095"
      LOGIN_BASE_URL: "http://localhost:8095"
      SPLASH_CONTEXT: ""
      CROWD_CONTEXT: "ROOT"
      CROWDID_CONTEXT: ""
      OPENID_CLIENT_CONTEXT: ""
    depends_on:
      - database
    links:
      - database
    external_links:
      - ${EXTERNAL_LINK_SERVICE}:${EXTERNAL_LINK_NAME}
    labels:
      rap.host: ${DOMAIN_NAME}
      rap.port: 7990
      rap.le_host: ${DOMAIN_NAME}

  database:
    image: postgres:9.4
    restart: always
    volumes:
      - ${DB_DATA_PATH}:/var/lib/postgresql/data