.catalog:
  name: "Atlassian Crowd by ReidWeb"
  version: "3.0.1"
  description: "Atlassian Crowd identity service provider"
  uuid: crowd
  minimum_rancher_version: v1.5.5
  questions:
      - variable: DATA_PATH
        label: Local path to data directory for Crowd or ref name
        description: Local path to data directory for Crowd or ref name
        required: true
        type: string
        default: "crowd-data"
      - variable: DB_DATA_PATH
        label: Local path to data directory for Crowd DB or ref name
        description: Local path to data directory for Crowd DB or ref name
        required: true
        type: string
        default: "/home/atlassian/database-data/crowd"
      - variable: PROXY_NAME
        label: Name for proxy setup in crowd, leave blank if not doing so
        description: Name for proxy setup in crowd, leave blank if not doing so
        required: false
        type: string
        default: "crowd.np.docker.reidweb.com"
      - variable: PROXY_PORT
        label: Port for proxy setup in crowd, leave blank if not doing so
        description: Name for proxy setup in crowd, leave blank if not doing so
        required: false
        type: enum
        options:
          - ""
          - "80"
      - variable: PROXY_SCHEME
        label: Scheme for proxy setup in crowd, leave blank if not doing so
        description: Scheme for proxy setup in crowd, leave blank if not doing so
        required: false
        type: enum
        options:
          - ""
          - "http"
      - variable: EXTERNAL_LINK_SERVICE
        label: An external service to link to, such as an OpenLDAP service instance.
        description: Select an external service to link to
        required: false
        type: service
      - variable: EXTERNAL_LINK_NAME
        label: Name at which make external service accessible at within this service
        description: Name at which make external service accessible at within this service
        required: false
        default: ldap
        type: string
crowd:
  scale: 1
  health_check:
    port: 8095
    interval: 2000
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: recreate
    healthy_threshold: 2
    response_timeout: 2000
database:
  scale: 1
  health_check:
    port: 5432
    interval: 2000
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: recreate
    healthy_threshold: 2
    response_timeout: 2000