.catalog:
  name: "OpenLDAP"
  version: "1.1.2"
  description: "OpenLDAP instance"
ldap-host:
  scale: 1
  health_check:
    port: 389
    interval: 2000
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: recreate
    healthy_threshold: 2
    response_timeout: 2000
ldap-admin:
  scale: 1
  health_check:
    port: 8029
    interval: 2000
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: recreate
    healthy_threshold: 2
    response_timeout: 2000
