.catalog:
  name: "OpenLDAP"
  version: "1.1.3"
  description: "OpenLDAP Software is an open source implementation of the Lightweight Directory Access Protocol."
  questions:
    - variable: "domain_name"
      label: "Domain"
      description: |
        The domain name for this OpenLDAP installation
      type: "string"
      default: "example.com"
      required: true
    - variable: "org_name"
      label: "Organisation"
      description: |
        The org name.
      type: "string"
      default: "Example Ltd."
      required: true
    - variable: "admin_pwd"
      label: "Admin password"
      description: |
        The default admin password
      type: "string"
      default: "adm1n"
      required: true
    - variable: "readonly_user"
      label: "Read only user"
      description: |
        Whether read only user should be created by default
      type: "boolean"
      default: true
      required: true
    - variable: "base_dn"
      label: "Base domain name"
      description: |
        The base domain name
      type: "string"
      default: "dc=example,dc=com"
      required: true
    - variable: "readonly_user_username"
      label: "Read only user username"
      description: |
        User name for read only user
      type: "string"
      default: "readonly"
      required: true
    - variable: "readonly_user_password"
      label: "Read only user user password"
      description: |
        User name for read only user
      type: "string"
      default: "readonly"
      required: true
    - variable: "admin_email"
      label: "Administrator email"
      description: |
        Administrator's email address
      type: "string"
      default: "you@example.com"
      required: true
    - variable: "client_tls"
      label: "PHPLDAPAdmin UI client TLS"
      description: |
        Whether to enforce client TLS
      type: "boolean"
      default: false
      required: true
    - variable: "ldap_external_port"
      label: "LDAP bind port"
      description: |
        Host port to bind LDAP to
      type: "int"
      default: "389"
      required: true
    - variable: "ldap_tls_port"
      label: "LDAP bind port"
      description: |
        Host port to bind LDAP to for TLS
      type: "int"
      default: "636"
      required: true
    - variable: "cert_path"
      label: "Path to certificate directory"
      description: |
        Path to certificate directory
      type: "string"
      required: false
      default: "/data/openldap-certs"
    - variable: "ui_hostname"
      label: "NGINX target host name"
      description: |
        NGINX target host name
      type: "string"
      default: "ldap.np.docker.reidweb.com"
      required: true
ldap-host:
  scale: 1
  health_check:
    port: 389
    interval: 2000
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: recreate
    healthy_threshold: 2
    response_timeout: 2000
ldap-admin:
  scale: 1
