name: VMWare Harbor by ReidWeb
description: |
  Enterprise Class Container Registry by VMWare
version: 1.1.1-1-rev1
category: Private Container Registry
projectURL: https://github.com/vmware/harbor 
license: Apache License 2.0 
