name: VMWare Harbor by ReidWeb
description: |
  Enterprise Class Container Registry by VMWare
version: 1.4.0
category: Private Container Registry
projectURL: https://github.com/vmware/harbor 
license: Apache License 2.0 
