version: '2'
services:
  bitbucket:
    image: atlassian/bitbucket-server:5.2.0
    volumes:
      - ${DATA_PATH}:/var/atlassian/application-data/bitbucket
    restart: always
    ports:
      - 7999:7999
    environment:
      SERVER_SECURE: ${SERVER_SECURE}
      SERVER_SCHEME: ${PROXY_SCHEME}
      SERVER_PROXY_PORT: ${PROXY_PORT}
      SERVER_PROXY_NAME: ${PROXY_NAME}
      ELASTICSEARCH_ENABLED: ${ELASTICSEARCH_ENABLED}
    links:
      - database
    depends_on:
      - database
    external_links:
      - ${CROWD_SERVICE}:crowd
    labels:
      traefik.enable: ${SHOULD_PROXY}
      traefik.domain: ${PROXY_NAME}
      traefik.port: ${PROXY_PORT}
      traefik.protocol: https
      traefik.acme: true
  database:
    image: postgres:9.4
    restart: always
    volumes:
      - ${DB_DATA_PATH}:/var/lib/postgresql/data