version: '2'
services:
  bitbucket:
    image: atlassian/bitbucket-server:5.2.0
    restart: always
    links:
      - database
    external_links:
      - crowd/crowd:crowd
    volumes:
      - bitbucket-data:/var/atlassian/application-data/bitbucket

  database:
    image: postgres:9.4
    restart: always
    volumes:
      - bitbucket-db-data:/var/lib/postgresql/data