version: '2'
volumes: #most volumes mappings require optimization (now all volumes map all containers) 
  etcjobservice:
    #external: true
    driver: ${volumedriver}
  etcnginx:
    #external: true
    driver: ${volumedriver}
  etcregistry:
    #external: true
    driver: ${volumedriver}
  etcui:
    #external: true
    driver: ${volumedriver}
  configjobservice:
    #external: true
    driver: ${volumedriver}
  configdb:
    #external: true
    driver: ${volumedriver}
  configui:
    #external: true
    driver: ${volumedriver}
  configadminserver:
    #external: true
    driver: ${volumedriver}
  data: #according to the eng team this is not even needed (but leaving it in for consistency)
    #external: true
    driver: ${volumedriver}
  data-registry:
    #external: true
    driver: ${volumedriver}
  data-database:
    #external: true
    driver: ${volumedriver}
  data-job_logs:
    #external: true
    driver: ${volumedriver}
  data-ca_download:
    #external: true
    driver: ${volumedriver}
  data-config:
    #external: true
    driver: ${volumedriver}
  confignotary:
    #external: true
    driver: ${volumedriver}
  confignotarysigner:
    #external: true
    driver: ${volumedriver}
  notary-mysql-initdb:
    #external: true
    driver: ${volumedriver}
  notary-db-data:
    #external: true
    driver: ${volumedriver}
  clair-db-data:
    #external: true
    driver: ${volumedriver}
  clair-postgresql-init.d:
    #external: true
    driver: ${volumedriver}
  clairconfig:
    #external: true
    driver: ${volumedriver}
services:
  harbor-setupwrapper:
    image: reidweb/harbor-setupwrapper:latest
    container_name: harbor-setupwrapper
    environment:
      - HARBORHOSTNAME=reg.np.docker.reidweb.com
      - HARBOR_ADMIN_PASSWORD=${harbor_admin_password}
      - UI_URL_PROTOCOL=https
      - SELF_REGISTRATION=off
    volumes:
      - data:/data
      - etcui:/etc/ui
      - etcjobservice:/etc/jobservice
      - etcregistry:/etc/registry
      - etcnginx:/etc/nginx
      - configdb:/configdb
      - configui:/configui
      - configjobservice:/configjobservice
      - configadminserver:/configadminserver
      - confignotary:/confignotary
      - confignotarysigner:/confignotarysigner
      - notary-mysql-initdb:/confignotarydb
      - /data/harbor-certs:/data/cert:ro
    command: ["/harbor/harbor-setupwrapper.sh"]
    network_mode: "none"
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.start_once: 'true'
  log:
    image: vmware/harbor-log:v1.1.1
    container_name: harbor-log
    restart: always
    volumes:
      - /var/log/harbor/:/var/log/docker/:z
    ports:
      - 1514:514
    labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
  registry:
    image: vmware/registry:photon-2.6.0
    container_name: registry
    restart: always
    volumes:
      - data-registry:/storage
      - data:/data
      - data-ca_download:/etc/ui/ca/
      - data-config:/etc/adminserver/config/
      - etcui:/etc/ui
      - etcjobservice:/etc/jobservice
      - etcregistry:/etc/registry
      - etcnginx:/etc/nginx
      - configdb:/configdb
      - configui:/configui
      - configjobservice:/configjobservice
      - configadminserver:/configadminserver
      - /data/harbor-certs:/data/cert:ro
    environment:
      - GODEBUG=netdns=cgo
    command:
      ["serve", "/etc/registry/config.yml"]
    depends_on:
      - log
      - harbor-setupwrapper
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "registry"
    networks:
      - harbor-clair
    labels:
      io.rancher.container.hostname_override: container_name
  mysql:
    image: vmware/harbor-db:v1.1.1
    container_name: harbor-db
    restart: always
    volumes:
      - data-database:/var/lib/mysql
      - data:/data:z
      - data-job_logs:/var/log/jobs
      - data-ca_download:/etc/ui/ca/
      - data-config:/etc/adminserver/config/
      - etcui:/etc/ui
      - etcjobservice:/etc/jobservice
      - etcregistry:/etc/registry
      - etcnginx:/etc/nginx
      - configdb:/configdb
      - configui:/configui
      - configjobservice:/configjobservice
      - configadminserver:/configadminserver
    depends_on:
      - log
      - harbor-setupwrapper
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "mysql"
    entrypoint:
      - /bin/sh
      - -c
    command:
      - /configdb/entrypointdb.sh
    labels:
      io.rancher.container.hostname_override: container_name
  adminserver:
    image: vmware/harbor-adminserver:v1.1.1
    container_name: harbor-adminserver
    restart: always
    volumes:
#      - /data/secretkey:/etc/adminserver/key
      - data-database:/var/lib/mysql
      - data:/data/:z
      - data-job_logs:/var/log/jobs
      - data-ca_download:/etc/ui/ca/
      - data-config:/etc/adminserver/config/
      - etcui:/etc/ui
      - etcjobservice:/etc/jobservice
      - etcregistry:/etc/registry
      - etcnginx:/etc/nginx
      - configdb:/configdb
      - configui:/configui
      - configjobservice:/configjobservice
      - configadminserver:/configadminserver
      - /data/harbor-certs:/data/cert:ro
    depends_on:
      - log
      - harbor-setupwrapper
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "adminserver"
    entrypoint:
      - /bin/sh
      - -c
    command:
      - /configadminserver/entrypointadminserver.sh
    labels:
      io.rancher.container.hostname_override: container_name
  ui:
    image: vmware/harbor-ui:v1.1.1
    container_name: harbor-ui
    restart: always
    volumes:
      - data:/data/:z
      - data-database:/var/lib/mysql
      - data-job_logs:/var/log/jobs
      - data-ca_download:/etc/ui/ca/
      - data-config:/etc/adminserver/config/
      - etcui:/etc/ui
      - etcjobservice:/etc/jobservice
      - etcregistry:/etc/registry
      - etcnginx:/etc/nginx
      - configdb:/configdb
      - configui:/configui
      - configjobservice:/configjobservice
      - configadminserver:/configadminserver
      - /data/harbor-certs:/data/cert:ro
    depends_on:
      - log
      - harbor-setupwrapper
      - adminserver
      - registry
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "ui"
    entrypoint:
      - /bin/sh
      - -c
    command:
      - /configui/entrypointui.sh
    networks:
      harbor-notary:
      harbor-clair:
        aliases:
          - harbor-ui
    labels:
      io.rancher.container.hostname_override: container_name
  jobservice:
    image: vmware/harbor-jobservice:v1.1.1
    container_name: harbor-jobservice
    restart: always
    volumes:
#      - /data/secretkey:/etc/jobservice/key:z
      - data:/data/:z
      - data-job_logs:/var/log/jobs
      - data-ca_download:/etc/ui/ca/
      - data-config:/etc/adminserver/config/
      - etcui:/etc/ui
      - etcjobservice:/etc/jobservice
      - etcregistry:/etc/registry
      - etcnginx:/etc/nginx
      - configdb:/configdb
      - configui:/configui
      - configjobservice:/configjobservice
      - configadminserver:/configadminserver
    depends_on:
      - log
      - harbor-setupwrapper
      - ui
      - adminserver
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "jobservice"
    entrypoint:
      - /bin/sh
      - -c
    networks:
      - harbor-clair
    command:
      - /configjobservice/entrypointjobservice.sh
    labels:
     io.rancher.container.hostname_override: container_name
  proxy:
    image: vmware/nginx:1.11.5-patched
    container_name: nginx
    restart: always
    volumes:
      - data-database:/var/lib/mysql
      - data:/data/:z
      - data-job_logs:/var/log/jobs
      - data-ca_download:/etc/ui/ca/
      - data-config:/etc/adminserver/config/
      - etcui:/etc/ui
      - etcjobservice:/etc/jobservice
      - etcregistry:/etc/registry
      - /data/harbor-nginx/nginx.conf:/etc/nginx/nginx.conf
      - /data/harbor-certs:/etc/nginx/cert:ro
      - configdb:/configdb
      - configui:/configui
      - configjobservice:/configjobservice
      - configadminserver:/configadminserver
    depends_on:
      - mysql
      - registry
      - ui
      - log
      - harbor-setupwrapper
    external_links: #these entries seem to be required for the proxy service to start correctly
      - registry
      - ui
      - mysql
      - jobservice
      - adminserver
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "proxy"
    networks:
      - harbor
      - harbor-notary
    labels:
      io.rancher.container.hostname_override: container_name
      com.reidweb.nginx.host: ${DOMAIN_NAMES}
      com.reidweb.nginx.port: 443
      com.reidweb.nginx.le_host: ${LE_DOMAIN_NAMES}
      com.reidweb.nginx.proto: "https"
# BEGIN NOTARY CONFIG
  notary-server:
    image: vmware/notary-photon:server-0.5.0
    container_name: notary-server
    restart: always
    networks:
      - notary-mdb
      - notary-sig
      - harbor-notary
    volumes:
      - confignotary:/config
    entrypoint:
      - /bin/sh
      - -c
    command:
      - /config/entrypointnotary.sh
    depends_on:
      - notary-db
      - notary-signer
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "notary-server"
  notary-signer:
    image: vmware/notary-photon:signer-0.5.0
    container_name: notary-signer
    restart: always
    networks:
      notary-mdb:
      notary-sig:
        aliases:
          - notarysigner
    volumes:
      - confignotarysigner:/config
    entrypoint:
      - /bin/sh
      - -c
    command:
      - /config/entrypointnotarysigner.sh
    depends_on:
      - notary-db
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "notary-signer"
  notary-db:
    image: vmware/harbor-notary-db:mariadb-10.1.10
    container_name: notary-db
    restart: always
    networks:
      notary-mdb:
        aliases:
          - mysql
    volumes:
      - notary-mysql-initdb:/docker-entrypoint-initdb.d
      - notary-db-data:/var/lib/mysql
    environment:
      - TERM=dumb
      - MYSQL_ALLOW_EMPTY_PASSWORD="true"
    command: mysqld --innodb_file_per_table
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "notary-db"
    labels:
      io.rancher.container.hostname_override: container_name
# END NOTARY CONFIG
# BEGIN CLAIR CONFIG
  postgres:
      container_name: clair-db
      image: vmware/postgresql:9.6.4-photon
      networks:
        harbor-clair:
          aliases:
            - postgres
      restart: always
      depends_on:
        - log
      volumes:
        - clairconfig:/clairconfig
        - clair-postgresql-init.d:/docker-entrypoint-initdb.d
        - clair-db-data:/var/lib/postgresql/data
      logging:
        driver: "syslog"
        options:  
          syslog-address: "tcp://127.0.0.1:1514"
          tag: "clair-db"
  clair:
      container_name: clair
      image: vmware/clair:v2.0.1-photon
      networks:
        - harbor-clair
      restart: always
      cpu_quota: 150000
      depends_on:
        - postgres
      volumes:
        - clairconfig:/config
      command: [-config, /config/config.yaml]
      logging:
        driver: "syslog"
        options:  
          syslog-address: "tcp://127.0.0.1:1514"
          tag: "clair"
# END CLAIR CONFIG
networks:
  harbor-notary:
    external: false
  notary-mdb:
    external: false
  notary-sig:
    external: false
  harbor-clair:
    external: false