version: '2'
services:
  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${CONFIG_PATH}:/etc/nginx/nginx.conf
      - ${CONFD_PATH}:/etc/nginx/conf.d
      - ${CERT_PATH}:/etc/letsencrypt
    external_links:
    - Bitbucket-server/bitbucket:bitbucket
    - Confluence/confluence:confluence
    - Jira-software/jira:jira
    - Crowd/crowd:crowd
