version: '2'
services:
  confluence:
    image: atlassian/confluence-server:6.3
    restart: always
    links:
      - database
    external_links:
      - crowd/crowd:crowd
    volumes:
      - confluence-data:/var/atlassian/confluence

  database:
    image: postgres:9.4
    restart: always
    volumes:
      - confluence-db-data:/var/lib/postgresql/data
