name: Eco Server
description: |
  Eco is an online game where players must collaborate to build a civilization in a world where everything they do affects the environment.
version: 0.7.25-beta
category: Video Game Servers
