version: '2'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - /etc/nginx/conf.d
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html 
      - /path/to/certs:/etc/nginx/certs:ro
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=''
      - io.rancher.sidekicks=docker-gen, letsencrypt-companion
  docker-gen:
    image: jwilder/docker-gen
    volumes_from:
      - nginx
    volumes: 
      - /path/to/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - ENABLE_IPV6=true
    depends_on:
      - nginx
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen=''
  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /path/to/certs:/etc/nginx/certs:rw
  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.np.docker.reidweb.com
      - LETSENCRYPT_HOST=whoami.np.docker.reidweb.com
      - LETSENCRYPT_EMAIL=ssl@reidweb.com
  