version: '2'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - /etc/nginx/conf.d:/etc/nginx/conf.d
      - /etc/nginx/vhost.d:/etc/nginx/vhost.d
      - /usr/share/nginx/html:/usr/share/nginx/html 
      - /etc/docker-nginx/certs:/etc/nginx/certs
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=''
      - io.rancher.sidekicks=docker-gen, letsencrypt-companion
  docker-gen:
    image: jwilder/docker-gen
    volumes_from:
      - nginx
    volumes: 
      - /home/reid/rancher/docker-gen/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
      - /var/run/docker.sock:/tmp/docker.sock
    environment:
      - ENABLE_IPV6=true
    depends_on:
      - nginx
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen=''
    command:
      - docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/docker-nginx/certs:/etc/nginx/certs
  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.np.docker.reidweb.com
      - LETSENCRYPT_HOST=whoami.np.docker.reidweb.com
      - LETSENCRYPT_EMAIL=ssl@reidweb.com
  