version: '2'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - /etc/nginx/conf.d:/etc/nginx/conf.d
      - /etc/nginx/vhost.d:/etc/nginx/vhost.d
      - /usr/share/nginx/html:/usr/share/nginx/html 
      - /etc/nginx/certs:/etc/nginx/certs:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
      - "io.rancher.sidekicks=docker-gen,letsencrypt-companion"
  docker-gen:
    image: jwilder/docker-gen
    restart: unless-stopped 
    volumes:
      - /etc/nginx/conf.d:/etc/nginx/conf.d
      - /home/reid/rancher/docker-gen/:/src/:ro
      - /etc/nginx/vhost.d:/etc/nginx/vhost.d
      - /etc/nginx/html:/usr/share/nginx/html
      - /etc/nginx/certs:/etc/nginx/certs:ro
      - /home/reid/rancher/docker-gen/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - ENABLE_IPV6=true
    links:
      - nginx
    depends_on:
      - nginx
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen: "true"
    entrypoint:
      - "/src/run.sh"
  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: unless-stopped
    volumes_from:
      - nginx
    volumes:
      - /etc/nginx/conf.d:/etc/nginx/conf.d
      - /etc/nginx/vhost.d:/etc/nginx/vhost.d
      - /etc/nginx/html:/usr/share/nginx/html
      - /etc/nginx/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock
